/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 15, 2020 at 12:47:53 AM Central Daylight Time
* Operating System: Version 13.5 (Build 17F75)
* Image Source: /private/var/containers/Bundle/Application/1CC42D00-8A5F-43B6-BAC4-093E6621D13D/TikTok.app/TikTok
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TikTok/TikTok-Structs.h>
#import <UIKitCore/UIViewController.h>
#import <TikTok/AWEFeedRootViewControllerAdapter.h>
#import <TikTok/AWERouterViewControllerProtocol.h>
#import <TikTok/POPAnimationDelegate.h>
#import <UIKit/UIGestureRecognizerDelegate.h>
#import <TikTok/AWEUserMessage.h>
#import <TikTok/AWEViewControllerRefreshable.h>
#import <TikTok/AWEReferenceTrackable.h>
#import <TikTok/AWEFeedRootViewController.h>

@protocol AWEFeedRootViewController <NSObject>
@required
-(BOOL)ifStoryViewIsOpen;

@end

#import <TikTok/AWEFeedRootViewControllerProtocol.h>

@protocol AWEFeedRefreshAnimationProtocol;
@class AWEFeedContainerViewController, AWEPublishRetryViewManager, UIPanGestureRecognizer, MPVolumeView, NSString;

@interface AWEFeedRootViewController : UIViewController <AWEFeedRootViewControllerAdapter, AWERouterViewControllerProtocol, POPAnimationDelegate, UIGestureRecognizerDelegate, AWEUserMessage, AWEViewControllerRefreshable, AWEReferenceTrackable, AWEFeedRootViewController, AWEFeedRootViewControllerProtocol> {

	BOOL _verticalPanActive;
	BOOL _tapticEngineTapped;
	BOOL _skylightButtonTapped;
	BOOL _isFirstAppear;
	BOOL _isViewDidAppear;
	BOOL _needsSetPureMode;
	BOOL _needsRefreshOnViewDidAppear;
	AWEFeedContainerViewController* _contentViewController;
	AWEPublishRetryViewManager* _retryViewManager;
	UIPanGestureRecognizer* _verticalPan;
	unsigned long long _verticalPanType;
	long long _refreshState;
	id<AWEFeedRefreshAnimationProtocol> _refreshAnimation;
	/*^block*/id _delayResetAudioSessionBlock;
	MPVolumeView* _volumeView;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,retain) AWEFeedContainerViewController * contentViewController;              //@synthesize contentViewController=_contentViewController - In the implementation block
@property (nonatomic,retain) UIPanGestureRecognizer * verticalPan;                                //@synthesize verticalPan=_verticalPan - In the implementation block
@property (assign,nonatomic) BOOL verticalPanActive;                                              //@synthesize verticalPanActive=_verticalPanActive - In the implementation block
@property (assign,nonatomic) BOOL tapticEngineTapped;                                             //@synthesize tapticEngineTapped=_tapticEngineTapped - In the implementation block
@property (assign,nonatomic) unsigned long long verticalPanType;                                  //@synthesize verticalPanType=_verticalPanType - In the implementation block
@property (assign,nonatomic) BOOL skylightButtonTapped;                                           //@synthesize skylightButtonTapped=_skylightButtonTapped - In the implementation block
@property (assign,nonatomic) long long refreshState;                                              //@synthesize refreshState=_refreshState - In the implementation block
@property (nonatomic,retain) id<AWEFeedRefreshAnimationProtocol> refreshAnimation;                //@synthesize refreshAnimation=_refreshAnimation - In the implementation block
@property (assign,nonatomic) BOOL isFirstAppear;                                                  //@synthesize isFirstAppear=_isFirstAppear - In the implementation block
@property (assign,nonatomic) BOOL isViewDidAppear;                                                //@synthesize isViewDidAppear=_isViewDidAppear - In the implementation block
@property (assign,nonatomic) BOOL needsSetPureMode;                                               //@synthesize needsSetPureMode=_needsSetPureMode - In the implementation block
@property (assign,nonatomic) BOOL needsRefreshOnViewDidAppear;                                    //@synthesize needsRefreshOnViewDidAppear=_needsRefreshOnViewDidAppear - In the implementation block
@property (nonatomic,copy) id delayResetAudioSessionBlock;                                        //@synthesize delayResetAudioSessionBlock=_delayResetAudioSessionBlock - In the implementation block
@property (nonatomic,retain) MPVolumeView * volumeView;                                           //@synthesize volumeView=_volumeView - In the implementation block
@property (nonatomic,retain) AWEPublishRetryViewManager * retryViewManager;                       //@synthesize retryViewManager=_retryViewManager - In the implementation block
+(void)_aweLazyRegisterLoad;
-(BOOL)configWithRouterParamDict:(id)arg1 ;
-(unsigned long long)directionForPan:(id)arg1 ;
-(BOOL)transition_enableCustomActionForSlideDirection:(unsigned long long)arg1 gestureRecognizer:(id)arg2 ;
-(id)transition_destinatedViewControllerForSlideDirection:(unsigned long long)arg1 gestureRecognizer:(id)arg2 ;
-(void)transition_performCustomActionForSlideDirection:(unsigned long long)arg1 gestureRecognizer:(id)arg2 ;
-(void)transition_didStartTransitionWithContext:(id)arg1 ;
-(id)enterFrom;
-(void)setIsFirstAppear:(BOOL)arg1 ;
-(id)getDeviceName;
-(void)didFinishLogin;
-(void)didFinishLogout;
-(id)referString;
-(id)awesst_enterFrom;
-(BOOL)awesst_isVideoPlayViewController;
-(id)awesst_additionalTrackerParams;
-(void)stopRefreshAnimation;
-(void)setRetryViewManager:(AWEPublishRetryViewManager *)arg1 ;
-(void)setVerticalPan:(UIPanGestureRecognizer *)arg1 ;
-(UIPanGestureRecognizer *)verticalPan;
-(void)setVerticalPanType:(unsigned long long)arg1 ;
-(void)setVerticalPanActive:(BOOL)arg1 ;
-(void)setRefreshAnimation:(id<AWEFeedRefreshAnimationProtocol>)arg1 ;
-(void)setRefreshState:(long long)arg1 ;
-(void)refreshWithType:(long long)arg1 completion:(/*^block*/id)arg2 ;
-(void)setTapticEngineTapped:(BOOL)arg1 ;
-(unsigned long long)verticalPanType;
-(BOOL)tapticEngineTapped;
-(id<AWEFeedRefreshAnimationProtocol>)refreshAnimation;
-(AWEPublishRetryViewManager *)retryViewManager;
-(BOOL)verticalPanActive;
-(void)setNeedsSetPureMode:(BOOL)arg1 ;
-(BOOL)needsSetPureMode;
-(void)setIsViewDidAppear:(BOOL)arg1 ;
-(BOOL)isViewDidAppear;
-(id)feedDiscoverEntranceView;
-(long long)getRefreshState;
-(void)showAlertViewWhenEnteredAgreementWebViewController;
-(void)_addPublishRetryView;
-(void)didReceiveAWEAwemeFeedInterestManagerSelectionNotification:(id)arg1 ;
-(BOOL)cancelTransitionDestinatedViewControllerForSlideDirection;
-(BOOL)cancelTransitionDestinatedViewControllerForSlideDirectionOnTransitionTriggerDirectionLeft;
-(BOOL)cancelTransitionDestinatedViewControllerForSlideDirectionOnTransitionTriggerDirectionRight;
-(void)handlePostAdsActionIfNeeded;
-(void)handelCarrierService;
-(float)resetColdLaunchPlayerVolume;
-(void)handleBridgeBroadcast:(id)arg1 ;
-(void)p_resetToPlayBack;
-(void)p_resetAudioSessionCategory;
-(id)delayResetAudioSessionBlock;
-(void)setDelayResetAudioSessionBlock:(id)arg1 ;
-(void)p_delayResetAudioSessionCategory;
-(float)calculatorVoluem:(BOOL)arg1 conservativeVolume:(float)arg2 ;
-(id)volumeSider;
-(BOOL)ifStoryViewIsOpen;
-(void)setVeticalPanEnabled:(BOOL)arg1 ;
-(void)disableRefreshGesture:(BOOL)arg1 ;
-(void)cancelRefreshing;
-(BOOL)skylightButtonTapped;
-(void)setSkylightButtonTapped:(BOOL)arg1 ;
-(BOOL)needsRefreshOnViewDidAppear;
-(void)setNeedsRefreshOnViewDidAppear:(BOOL)arg1 ;
-(id)init;
-(void)dealloc;
-(BOOL)gestureRecognizerShouldBegin:(id)arg1 ;
-(BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2 ;
-(void)setContentViewController:(AWEFeedContainerViewController *)arg1 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(AWEFeedContainerViewController *)contentViewController;
-(void)viewDidAppear:(BOOL)arg1 ;
-(long long)preferredStatusBarStyle;
-(long long)refreshState;
-(BOOL)prefersStatusBarHidden;
-(MPVolumeView *)volumeView;
-(void)handlePanGesture:(id)arg1 ;
-(BOOL)isFirstAppear;
-(BOOL)refreshWithCompletion:(/*^block*/id)arg1 ;
-(id)discoveryController;
-(void)pop_animationDidStop:(id)arg1 finished:(BOOL)arg2 ;
-(void)setSystemVolume:(float)arg1 ;
-(void)setVolumeView:(MPVolumeView *)arg1 ;
@end

